// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtikqyv8qamAnFwJznxb6FehdzCJs6NPc',
    appId: '1:209360868268:web:1b51b77d66be82064c6009',
    messagingSenderId: '209360868268',
    projectId: 'emogurd',
    authDomain: 'emogurd.firebaseapp.com',
    storageBucket: 'emogurd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9BhE5SVkRdoVs_eMqt-2PanwGilXIwY',
    appId: '1:209360868268:android:1c64ca66c7873ec84c6009',
    messagingSenderId: '209360868268',
    projectId: 'emogurd',
    storageBucket: 'emogurd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJMRo0OBjBk7m-hIDyL3KFHtTTy-1v3xo',
    appId: '1:209360868268:ios:95862b8c88aa5dc54c6009',
    messagingSenderId: '209360868268',
    projectId: 'emogurd',
    storageBucket: 'emogurd.appspot.com',
    iosBundleId: 'com.example.emoGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJMRo0OBjBk7m-hIDyL3KFHtTTy-1v3xo',
    appId: '1:209360868268:ios:95862b8c88aa5dc54c6009',
    messagingSenderId: '209360868268',
    projectId: 'emogurd',
    storageBucket: 'emogurd.appspot.com',
    iosBundleId: 'com.example.emoGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtikqyv8qamAnFwJznxb6FehdzCJs6NPc',
    appId: '1:209360868268:web:94fb8df3a3f690ba4c6009',
    messagingSenderId: '209360868268',
    projectId: 'emogurd',
    authDomain: 'emogurd.firebaseapp.com',
    storageBucket: 'emogurd.appspot.com',
  );

}